# Generated by Django 5.0.1 on 2024-09-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_rename_language_languagemodel_language_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='intermediate_LanguageModel',
        ),
        migrations.RemoveField(
            model_name='resumemodel',
            name='user',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='language_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='LanguageModel',
        ),
        migrations.DeleteModel(
            name='resumeModel',
        ),
    ]
